2025-09-13 19:03:26,156 - INFO - httpx - HTTP Request: GET https://ca1.erpnext.cloud/api/method/frappe.auth.get_logged_user "HTTP/1.1 200 OK"
2025-09-13 19:03:26,157 - INFO - erpnext_client - GET /api/method/frappe.auth.get_logged_user - 200 - 0.82s
2025-09-13 19:03:29,070 - INFO - httpx - HTTP Request: GET https://ca1.erpnext.cloud/api/resource/Customer?limit_page_length=5 "HTTP/1.1 200 OK"
2025-09-13 19:03:29,074 - INFO - erpnext_client - GET /api/resource/Customer - 200 - 0.77s
2025-09-13 19:03:31,771 - INFO - httpx - HTTP Request: GET https://ca1.erpnext.cloud/api/resource/Customer?limit_page_length=1 "HTTP/1.1 200 OK"
2025-09-13 19:03:31,772 - INFO - erpnext_client - GET /api/resource/Customer - 200 - 0.41s
2025-09-13 19:03:34,050 - INFO - httpx - HTTP Request: GET https://ca1.erpnext.cloud/api/method/frappe.auth.get_logged_user "HTTP/1.1 200 OK"
2025-09-13 19:03:34,054 - INFO - erpnext_client - GET /api/method/frappe.auth.get_logged_user - 200 - 0.33s
2025-09-13 19:03:36,094 - INFO - httpx - HTTP Request: GET https://ca1.erpnext.cloud/api/resource/Customer?limit_page_length=5 "HTTP/1.1 200 OK"
2025-09-13 19:03:36,095 - INFO - erpnext_client - GET /api/resource/Customer - 200 - 0.52s
2025-09-13 19:03:38,186 - INFO - httpx - HTTP Request: GET https://ca1.erpnext.cloud/api/resource/Customer?limit_page_length=1 "HTTP/1.1 200 OK"
2025-09-13 19:03:38,187 - INFO - erpnext_client - GET /api/resource/Customer - 200 - 0.32s
2025-09-13 19:24:29,602 - INFO - httpx - HTTP Request: GET https://ca1.erpnext.cloud/api/method/frappe.auth.get_logged_user "HTTP/1.1 200 OK"
2025-09-13 19:24:29,604 - INFO - src.erpnext_client - GET /api/method/frappe.auth.get_logged_user - 200 - 0.40s
2025-09-13 19:24:32,359 - INFO - httpx - HTTP Request: POST https://ca1.erpnext.cloud/api/resource/Customer "HTTP/1.1 417 EXPECTATION FAILED"
2025-09-13 19:24:32,360 - ERROR - src.erpnext_client - HTTP 417 for POST /api/resource/Customer: {"exception":"frappe.exceptions.MandatoryError: [Customer, Test Customer 266194]: account_manager, default_price_list, sales_person, payment_terms","exc_type":"MandatoryError","exc":"[\"Traceback (most recent call last):\\n  File \\\"apps/frappe/frappe/app.py\\\", line 115, in application\\n    response = frappe.api.handle(request)\\n  File \\\"apps/frappe/frappe/api/__init__.py\\\", line 49, in handle\\n    data = endpoint(**arguments)\\n  File \\\"apps/frappe/frappe/api/v1.py\\\", line 42, in create_doc\\n    return frappe.new_doc(doctype, **data).insert()\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 310, in insert\\n    self._validate()\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 622, in _validate\\n    self._validate_mandatory()\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 956, in _validate_mandatory\\n    raise frappe.MandatoryError(\\nfrappe.exceptions.MandatoryError: [Customer, Test Customer 266194]: account_manager, default_price_list, sales_person, payment_terms\\n\"]","_server_messages":"[\"{\\\"message\\\": \\\"Error: Value missing for Customer: Account Manager\\\", \\\"title\\\": \\\"Message\\\"}\", \"{\\\"message\\\": \\\"Error: Value missing for Customer: Default Price List\\\", \\\"title\\\": \\\"Message\\\"}\", \"{\\\"message\\\": \\\"Error: Value missing for Customer: Sales Person\\\", \\\"title\\\": \\\"Message\\\"}\", \"{\\\"message\\\": \\\"Error: Value missing for Customer: Default Payment Terms Template\\\", \\\"title\\\": \\\"Message\\\"}\"]"}
2025-09-13 19:27:29,365 - INFO - httpx - HTTP Request: GET https://ca1.erpnext.cloud/api/method/frappe.auth.get_logged_user "HTTP/1.1 200 OK"
2025-09-13 19:27:29,367 - INFO - src.erpnext_client - GET /api/method/frappe.auth.get_logged_user - 200 - 0.63s
2025-09-13 19:27:31,797 - INFO - httpx - HTTP Request: GET https://ca1.erpnext.cloud/api/resource/Customer?limit_page_length=20 "HTTP/1.1 200 OK"
2025-09-13 19:27:31,801 - INFO - src.erpnext_client - GET /api/resource/Customer - 200 - 0.32s
2025-09-13 19:27:33,876 - INFO - httpx - HTTP Request: GET https://ca1.erpnext.cloud/api/resource/Customer?limit_page_length=20 "HTTP/1.1 200 OK"
2025-09-13 19:27:33,878 - INFO - src.erpnext_client - GET /api/resource/Customer - 200 - 0.32s
2025-09-13 19:31:03,120 - INFO - httpx - HTTP Request: GET https://ca1.erpnext.cloud/api/method/frappe.auth.get_logged_user "HTTP/1.1 200 OK"
2025-09-13 19:31:03,121 - INFO - src.erpnext_client - GET /api/method/frappe.auth.get_logged_user - 200 - 0.38s
2025-09-13 19:31:05,309 - INFO - httpx - HTTP Request: GET https://ca1.erpnext.cloud/api/resource/Customer?limit_page_length=20 "HTTP/1.1 200 OK"
2025-09-13 19:31:05,313 - INFO - src.erpnext_client - GET /api/resource/Customer - 200 - 0.31s
2025-09-13 19:31:07,337 - INFO - httpx - HTTP Request: GET https://ca1.erpnext.cloud/api/resource/Customer?limit_page_length=20 "HTTP/1.1 200 OK"
2025-09-13 19:31:07,338 - INFO - src.erpnext_client - GET /api/resource/Customer - 200 - 0.35s
2025-09-13 19:38:43,422 - INFO - httpx - HTTP Request: GET https://ca1.erpnext.cloud/api/method/frappe.auth.get_logged_user "HTTP/1.1 200 OK"
2025-09-13 19:38:43,423 - INFO - src.erpnext_client - GET /api/method/frappe.auth.get_logged_user - 200 - 0.63s
2025-09-13 19:38:46,031 - INFO - httpx - HTTP Request: POST https://ca1.erpnext.cloud/api/resource/Customer "HTTP/1.1 417 EXPECTATION FAILED"
2025-09-13 19:38:46,032 - ERROR - src.erpnext_client - HTTP 417 for POST /api/resource/Customer: {"exception":"frappe.exceptions.MandatoryError: [Customer, Test Customer 267048]: account_manager, default_price_list, sales_person, payment_terms","exc_type":"MandatoryError","exc":"[\"Traceback (most recent call last):\\n  File \\\"apps/frappe/frappe/app.py\\\", line 115, in application\\n    response = frappe.api.handle(request)\\n  File \\\"apps/frappe/frappe/api/__init__.py\\\", line 49, in handle\\n    data = endpoint(**arguments)\\n  File \\\"apps/frappe/frappe/api/v1.py\\\", line 42, in create_doc\\n    return frappe.new_doc(doctype, **data).insert()\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 310, in insert\\n    self._validate()\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 622, in _validate\\n    self._validate_mandatory()\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 956, in _validate_mandatory\\n    raise frappe.MandatoryError(\\nfrappe.exceptions.MandatoryError: [Customer, Test Customer 267048]: account_manager, default_price_list, sales_person, payment_terms\\n\"]","_server_messages":"[\"{\\\"message\\\": \\\"Error: Value missing for Customer: Account Manager\\\", \\\"title\\\": \\\"Message\\\"}\", \"{\\\"message\\\": \\\"Error: Value missing for Customer: Default Price List\\\", \\\"title\\\": \\\"Message\\\"}\", \"{\\\"message\\\": \\\"Error: Value missing for Customer: Sales Person\\\", \\\"title\\\": \\\"Message\\\"}\", \"{\\\"message\\\": \\\"Error: Value missing for Customer: Default Payment Terms Template\\\", \\\"title\\\": \\\"Message\\\"}\"]"}
2025-09-13 19:38:48,292 - INFO - httpx - HTTP Request: POST https://ca1.erpnext.cloud/api/resource/Customer "HTTP/1.1 417 EXPECTATION FAILED"
2025-09-13 19:38:48,293 - ERROR - src.erpnext_client - HTTP 417 for POST /api/resource/Customer: {"exception":"frappe.exceptions.MandatoryError: [Customer, Basic Test 267048]: account_manager, default_price_list, sales_person, payment_terms","exc_type":"MandatoryError","exc":"[\"Traceback (most recent call last):\\n  File \\\"apps/frappe/frappe/app.py\\\", line 115, in application\\n    response = frappe.api.handle(request)\\n  File \\\"apps/frappe/frappe/api/__init__.py\\\", line 49, in handle\\n    data = endpoint(**arguments)\\n  File \\\"apps/frappe/frappe/api/v1.py\\\", line 42, in create_doc\\n    return frappe.new_doc(doctype, **data).insert()\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 310, in insert\\n    self._validate()\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 622, in _validate\\n    self._validate_mandatory()\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 956, in _validate_mandatory\\n    raise frappe.MandatoryError(\\nfrappe.exceptions.MandatoryError: [Customer, Basic Test 267048]: account_manager, default_price_list, sales_person, payment_terms\\n\"]","_server_messages":"[\"{\\\"message\\\": \\\"Error: Value missing for Customer: Account Manager\\\", \\\"title\\\": \\\"Message\\\"}\", \"{\\\"message\\\": \\\"Error: Value missing for Customer: Default Price List\\\", \\\"title\\\": \\\"Message\\\"}\", \"{\\\"message\\\": \\\"Error: Value missing for Customer: Sales Person\\\", \\\"title\\\": \\\"Message\\\"}\", \"{\\\"message\\\": \\\"Error: Value missing for Customer: Default Payment Terms Template\\\", \\\"title\\\": \\\"Message\\\"}\"]"}
2025-09-13 20:00:19,240 - INFO - httpx - HTTP Request: GET https://ca1.erpnext.cloud/api/method/frappe.auth.get_logged_user "HTTP/1.1 200 OK"
2025-09-13 20:00:19,241 - INFO - src.erpnext_client - GET /api/method/frappe.auth.get_logged_user - 200 - 0.82s
2025-09-13 20:00:22,749 - INFO - httpx - HTTP Request: POST https://ca1.erpnext.cloud/api/resource/Item "HTTP/1.1 200 OK"
2025-09-13 20:00:22,752 - INFO - src.erpnext_client - POST /api/resource/Item - 200 - 1.28s
2025-09-13 20:00:25,165 - INFO - httpx - HTTP Request: GET https://ca1.erpnext.cloud/api/resource/Item/Api%20Item "HTTP/1.1 200 OK"
2025-09-13 20:00:25,166 - INFO - src.erpnext_client - GET /api/resource/Item/Api Item - 200 - 0.49s
2025-09-13 20:00:56,208 - INFO - httpx - HTTP Request: GET https://ca1.erpnext.cloud/api/method/frappe.auth.get_logged_user "HTTP/1.1 200 OK"
2025-09-13 20:00:56,209 - INFO - src.erpnext_client - GET /api/method/frappe.auth.get_logged_user - 200 - 0.37s
2025-09-13 20:00:58,461 - INFO - httpx - HTTP Request: POST https://ca1.erpnext.cloud/api/resource/Item "HTTP/1.1 409 CONFLICT"
2025-09-13 20:00:58,462 - ERROR - src.erpnext_client - HTTP 409 for POST /api/resource/Item: {"exception":"frappe.exceptions.DuplicateEntryError: ('Item', 'Api Item', IntegrityError(1062, \"Duplicate entry 'Api Item' for key 'PRIMARY'\"))","exc_type":"DuplicateEntryError","exc":"[\"Traceback (most recent call last):\\n  File \\\"apps/frappe/frappe/model/base_document.py\\\", line 576, in db_insert\\n    frappe.db.sql(\\n  File \\\"apps/frappe/frappe/database/database.py\\\", line 230, in sql\\n    self._cursor.execute(query, values)\\n  File \\\"env/lib/python3.10/site-packages/pymysql/cursors.py\\\", line 153, in execute\\n    result = self._query(query)\\n  File \\\"env/lib/python3.10/site-packages/pymysql/cursors.py\\\", line 322, in _query\\n    conn.query(q)\\n  File \\\"env/lib/python3.10/site-packages/pymysql/connections.py\\\", line 563, in query\\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\\n  File \\\"env/lib/python3.10/site-packages/pymysql/connections.py\\\", line 825, in _read_query_result\\n    result.read()\\n  File \\\"env/lib/python3.10/site-packages/pymysql/connections.py\\\", line 1199, in read\\n    first_packet = self.connection._read_packet()\\n  File \\\"env/lib/python3.10/site-packages/pymysql/connections.py\\\", line 775, in _read_packet\\n    packet.raise_for_error()\\n  File \\\"env/lib/python3.10/site-packages/pymysql/protocol.py\\\", line 219, in raise_for_error\\n    err.raise_mysql_exception(self._data)\\n  File \\\"env/lib/python3.10/site-packages/pymysql/err.py\\\", line 150, in raise_mysql_exception\\n    raise errorclass(errno, errval)\\npymysql.err.IntegrityError: (1062, \\\"Duplicate entry 'Api Item' for key 'PRIMARY'\\\")\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \\\"apps/frappe/frappe/app.py\\\", line 115, in application\\n    response = frappe.api.handle(request)\\n  File \\\"apps/frappe/frappe/api/__init__.py\\\", line 49, in handle\\n    data = endpoint(**arguments)\\n  File \\\"apps/frappe/frappe/api/v1.py\\\", line 42, in create_doc\\n    return frappe.new_doc(doctype, **data).insert()\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 320, in insert\\n    self.db_insert(ignore_if_duplicate=ignore_if_duplicate)\\n  File \\\"apps/frappe/frappe/model/base_document.py\\\", line 603, in db_insert\\n    raise frappe.DuplicateEntryError(self.doctype, self.name, e)\\nfrappe.exceptions.DuplicateEntryError: ('Item', 'Api Item', IntegrityError(1062, \\\"Duplicate entry 'Api Item' for key 'PRIMARY'\\\"))\\n\"]","_server_messages":"[\"{\\\"message\\\": \\\"Item <strong>Api Item</strong> already exists\\\", \\\"title\\\": \\\"Duplicate Name\\\", \\\"indicator\\\": \\\"red\\\"}\"]"}
2025-09-13 20:01:01,000 - INFO - httpx - HTTP Request: POST https://ca1.erpnext.cloud/api/resource/Item "HTTP/1.1 417 EXPECTATION FAILED"
2025-09-13 20:01:01,001 - ERROR - src.erpnext_client - HTTP 417 for POST /api/resource/Item: {"exception":"frappe.exceptions.MandatoryError: [Item, Basic Test 268380]: stock_uom","exc_type":"MandatoryError","exc":"[\"Traceback (most recent call last):\\n  File \\\"apps/frappe/frappe/app.py\\\", line 115, in application\\n    response = frappe.api.handle(request)\\n  File \\\"apps/frappe/frappe/api/__init__.py\\\", line 49, in handle\\n    data = endpoint(**arguments)\\n  File \\\"apps/frappe/frappe/api/v1.py\\\", line 42, in create_doc\\n    return frappe.new_doc(doctype, **data).insert()\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 310, in insert\\n    self._validate()\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 622, in _validate\\n    self._validate_mandatory()\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 956, in _validate_mandatory\\n    raise frappe.MandatoryError(\\nfrappe.exceptions.MandatoryError: [Item, Basic Test 268380]: stock_uom\\n\"]","_server_messages":"[\"{\\\"message\\\": \\\"Error: Value missing for Item: Default Unit of Measure\\\", \\\"title\\\": \\\"Message\\\"}\"]"}
2025-09-17 04:32:56,833 - INFO - httpx - HTTP Request: GET https://ca1.erpnext.cloud/api/method/frappe.auth.get_logged_user "HTTP/1.1 200 OK"
2025-09-17 04:32:56,835 - INFO - src.erpnext_client - GET /api/method/frappe.auth.get_logged_user - 200 - 0.84s
2025-09-17 04:34:14,293 - INFO - httpx - HTTP Request: GET https://ca1.erpnext.cloud/api/resource/Item/52015 "HTTP/1.1 200 OK"
2025-09-17 04:34:14,297 - INFO - src.erpnext_client - GET /api/resource/Item/52015 - 200 - 0.49s
2025-09-17 04:34:30,900 - INFO - httpx - HTTP Request: GET https://ca1.erpnext.cloud/api/method/frappe.auth.get_logged_user "HTTP/1.1 200 OK"
2025-09-17 04:34:30,901 - INFO - src.erpnext_client - GET /api/method/frappe.auth.get_logged_user - 200 - 0.41s
2025-09-17 04:34:43,721 - INFO - httpx - HTTP Request: DELETE https://ca1.erpnext.cloud/api/resource/Item/52015 "HTTP/1.1 403 FORBIDDEN"
2025-09-17 04:34:43,722 - ERROR - src.erpnext_client - HTTP 403 for DELETE /api/resource/Item/52015: {"exception":"frappe.exceptions.PermissionError: User not allowed to delete Item: 52015","exc_type":"PermissionError","exc":"[\"Traceback (most recent call last):\\n  File \\\"apps/frappe/frappe/app.py\\\", line 115, in application\\n    response = frappe.api.handle(request)\\n  File \\\"apps/frappe/frappe/api/__init__.py\\\", line 49, in handle\\n    data = endpoint(**arguments)\\n  File \\\"apps/frappe/frappe/api/v1.py\\\", line 64, in delete_doc\\n    frappe.delete_doc(doctype, name, ignore_missing=False)\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 1370, in delete_doc\\n    return frappe.model.delete_doc.delete_doc(\\n  File \\\"apps/frappe/frappe/model/delete_doc.py\\\", line 122, in delete_doc\\n    check_permission_and_not_submitted(doc)\\n  File \\\"apps/frappe/frappe/model/delete_doc.py\\\", line 246, in check_permission_and_not_submitted\\n    frappe.msgprint(\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 574, in msgprint\\n    _raise_exception()\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 525, in _raise_exception\\n    raise exc\\nfrappe.exceptions.PermissionError: User not allowed to delete Item: 52015\\n\"]","_server_messages":"[\"{\\\"message\\\": \\\"User <strong>development@erpcloud.systems</strong> does not have access to this document: Item - 52015\\\", \\\"title\\\": \\\"Message\\\"}\", \"{\\\"message\\\": \\\"User not allowed to delete Item: 52015\\\", \\\"title\\\": \\\"Message\\\", \\\"indicator\\\": \\\"red\\\", \\\"raise_exception\\\": 1, \\\"__frappe_exc_id\\\": \\\"f68ff36094761378ae778bc48ef76000041551f5e891027a297936fc\\\"}\"]"}
2025-09-17 04:36:10,755 - INFO - httpx - HTTP Request: GET https://ca1.erpnext.cloud/api/method/frappe.auth.get_logged_user "HTTP/1.1 200 OK"
2025-09-17 04:36:10,756 - INFO - src.erpnext_client - GET /api/method/frappe.auth.get_logged_user - 200 - 0.46s
2025-09-17 04:36:19,005 - INFO - httpx - HTTP Request: GET https://ca1.erpnext.cloud/api/resource/Item/52015 "HTTP/1.1 200 OK"
2025-09-17 04:36:19,006 - INFO - src.erpnext_client - GET /api/resource/Item/52015 - 200 - 0.48s
